"""'Int'

Revision ID: 071e6b6f3423
Revises: 7283b64d79fc
Create Date: 2023-04-13 23:43:10.035585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071e6b6f3423'
down_revision = '7283b64d79fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimerecords', sa.Column('station', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'crimerecords', 'user', ['station'], ['id'])
    op.alter_column('location', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'stationuser_id')
    op.drop_column('location', 'stationcrime_id')
    op.add_column('user', sa.Column('station', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'station')
    op.add_column('location', sa.Column('stationcrime_id', sa.INTEGER(), nullable=True))
    op.add_column('location', sa.Column('stationuser_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'location', 'crimerecords', ['stationcrime_id'], ['id'])
    op.create_foreign_key(None, 'location', 'user', ['stationuser_id'], ['id'])
    op.alter_column('location', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'crimerecords', type_='foreignkey')
    op.drop_column('crimerecords', 'station')
    # ### end Alembic commands ###
