"""'Int'

Revision ID: 194cab1f4ca5
Revises: 
Create Date: 2023-08-02 15:14:03.404286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194cab1f4ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crimerecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('media_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('profile_pic2')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('about',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)

    with op.batch_alter_table('crimerecords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic2', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('media_data')
        batch_op.drop_column('media_type')
        batch_op.drop_column('evidence')

    # ### end Alembic commands ###
