"""'Int'

Revision ID: b95c07cd059b
Revises: 
Create Date: 2023-05-03 19:53:23.734888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95c07cd059b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimerecords', sa.Column('motive', sa.String(length=64), nullable=True))
    op.add_column('crimerecords', sa.Column('nationality', sa.String(length=32), nullable=True))
    op.add_column('crimerecords', sa.Column('phone_No', sa.String(length=64), nullable=True))
    op.add_column('crimerecords', sa.Column('medicals', sa.String(length=64), nullable=True))
    op.add_column('crimerecords', sa.Column('address', sa.String(length=128), nullable=True))
    op.drop_column('crimerecords', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimerecords', sa.Column('image', sa.BLOB(), nullable=True))
    op.drop_column('crimerecords', 'address')
    op.drop_column('crimerecords', 'medicals')
    op.drop_column('crimerecords', 'phone_No')
    op.drop_column('crimerecords', 'nationality')
    op.drop_column('crimerecords', 'motive')
    # ### end Alembic commands ###
